// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AgeschoolageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ageschoolage() {
    driver.get("https://www.envisionfinancial.ca/tools-calculators/calculators/resp-calculator");
    driver.manage().window().setSize(new Dimension(707, 697));
    driver.switchTo().frame(0);
    driver.findElement(By.id("calcJSChildAge")).click();
    driver.findElement(By.id("calcJSChildAge")).sendKeys("21");
    driver.findElement(By.id("ageStartSchool")).click();
    driver.findElement(By.id("calcJS-errorMesgTitle")).click();
    driver.findElement(By.id("calcTopError")).click();
    assertThat(driver.findElement(By.id("calcJS-errorMesgTitle")).getText(), is("The age must be younger than when the child will begin post-secondary education."));
  }
}
