// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PositivetestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void positivetest() {
    driver.get("https://www.envisionfinancial.ca/tools-calculators/calculators/resp-calculator");
    driver.manage().window().setSize(new Dimension(1920, 1015));
    driver.switchTo().frame(0);
    driver.findElement(By.id("calcJSChildAge")).click();
    driver.findElement(By.id("calcJSChildAge")).sendKeys("2");
    driver.findElement(By.id("ageStartSchool")).click();
    driver.findElement(By.id("yearsAtSchool")).click();
    driver.findElement(By.id("calcJSTuition")).click();
    driver.findElement(By.id("calcJSTuition")).click();
    driver.findElement(By.id("calcJSTuition")).sendKeys("$10,000");
    driver.findElement(By.id("calcJSTuition")).click();
    driver.findElement(By.id("roomAndBoard")).click();
    driver.findElement(By.id("roomAndBoard")).sendKeys("$10,000");
    driver.findElement(By.id("calcJSInflation")).click();
    driver.findElement(By.id("calcJSInflation")).sendKeys("2.1");
    driver.findElement(By.id("netFamilyIncome")).click();
    driver.findElement(By.cssSelector("#netFamilyIncome > option:nth-child(2)")).click();
    driver.findElement(By.id("currentEduSavings")).click();
    driver.findElement(By.id("annualRateOfReturn")).click();
    driver.findElement(By.id("contributionAmount")).click();
    driver.findElement(By.id("contributionAmount")).sendKeys("$350");
    driver.findElement(By.id("contributionFrequency")).click();
    driver.findElement(By.cssSelector("#contributionFrequency > option:nth-child(1)")).click();
    assertThat(driver.findElement(By.id("respSurplus")).getText(), is("$11,192.32"));
  }
}
